### ISSUE TITLE
Ribbon renderer

### ISSUE THREAD

**Issue by jaimergp** [chemlab/chemlab#135]
Hi Gabriele!

I was wondering if chemlab could have support for ribbon depiction of proteins. Is that feasible?

Thank you very much!

**Comment by gabrielelanaro** [comment]
Sure this is not a hard task. Do you have a test file in mind that would you like to be rendered/supported?

**Comment by jaimergp** [comment]
Any protein should do, actually. I opened PDB and 4WF6 was featured. It has alpha-helices, beta-sheets and coils, so it should be a good test!

http://www.rcsb.org/pdb/explore/explore.do?structureId=4WF6

**Comment by jaimergp** [comment]
Hi again :)

Any updates on this, Gabriele?

Thanks!

**Comment by gabrielelanaro** [comment]
Hi! At the moment I'm trying to unifying the backends so that we can render the exact same scene in the qt/notebook/povray backend seamlessly, so that you can easily produce high res pictures for papers. As a part of this I'll also make the first prototype for ribbon renderer to make sure that the new architecture supports that use case as well.

**Comment by jaimergp** [comment]
Oh, that's great! I'll be more than glad to help you test that :)
