### ISSUE TITLE
"Pythonizing" chemlab.io.IOHandler API

### ISSUE THREAD

**Issue by jaimergp** [chemlab/chemlab#145]
I was checking the [API docs](https://chemlab.readthedocs.org/en/latest/api/chemlab.io.html), and found the `IOHandler` methods a bit confusing, especially the features thing.

IOHandler supplies three methods for feature reading: `can_read`, `check_feature`, `read`. I am OK with `can_read`, but why having explicit methods for `check_feature` and `read` when we have the dict API? 

I mean, `check_feature` could be implemented as the Python [`__contains__`](https://docs.python.org/3/reference/datamodel.html#object.__contains__) method, while `read()` is literally a getter, which can be *Pythonized* as a [`__getitem__`](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) or `get(feature, default)` methods. 

Besides being more pythonic (whatever that means anyway), it would give a chance to implement trivial but useful methods like `.keys()`, which would return a list of available features for that datafile.

I am just curious why you decided to implement it like that :) Of course, I wouldn't mind working on a PR to tackle this.

**Comment by gabrielelanaro** [comment]
Hi! The original idea was that the IOHandler is more similar to a file, in the sense that it is something that can be either written or read.  So, in general there should be features that can be written and/or read. This is a bit different from a dictionary when you expect to be able to read and write every "key".

That said, I have grown not liking this IOHandler business because it's not implemented very consistently and not very clear overall. 

I tried to develop this metaphor to "unify" all the chemical file format but I'm starting to think this is not a good idea.

I was thinking about something else altogether, that could be the best solution overall, and is consistent with what other packages have been doing all along (numpy, scipy, pandas, mdtraj etc.). Writing plain and simple:

```
read_gro("file.gro", options...)
write_gro(/...)
read_xtc(...)
write_xtc(...)
...
```

Regarding using the dict interface, I think this would be a very good idea for the chemlab.db package. In a db there is much more consistency in writing, reading, and the dict interface would be great.

**Comment by jaimergp** [comment]
Oh, I see why now. I was thinking that the new solution would be *inelegant*, but the more I think about it, the more I like it. With that interface, listing all compatible formats would be as easy as chemlab.io.read + press Tab in IPython, and the same for write methods. Yup, I like it!

I am glad that my proposal at least works for other parts of chemlab, though! Should I change the title of this issue or do you prefer to close this one and create a separate one?

**Comment by gabrielelanaro** [comment]
Let's open separate issues and close this one (we can always reference this one for motivation)
